rbacApiVersion: authorization.openshift.io
namespace: olm-sandbox
catalog_namespace: olm-sandbox
alm:
  replicaCount: 1
  image:
    ref: quay.io/coreos/olm:0.5.0
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog:
  replicaCount: 1
  image:
    ref: quay.io/coreos/catalog:0.5.0
    pullPolicy: IfNotPresent
  service:
    internalPort: 8080

catalog_sources:
 - tectonic-ocs
 - tectonic-components
