# This file defines the ClusterServiceVersion (CSV) to tell the catalog how to display, create and
# manage the application as a whole. If changes are made to the CRD for this application kind,
# make sure to replace those references below as well.
apiVersion: app.coreos.com/v1alpha1
kind: ClusterServiceVersion-v1
metadata:
  name: echo-operator.v0.0.2
spec:
  install:
    strategy: deployment
    spec:
      permissions:
      - serviceAccountName: echo-operator
        rules:
        - apiGroups:
          - echo.redhat.com
          resources:
          - "*"
          verbs:
          - "*"
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - "*"
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - "*"
      deployments:
      - name: echo-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: echo-operator
          template:
            metadata:
              labels:
                app: echo-operator
            spec:
              containers:
                - name: echo-operator
                  image: docker.io/tohinkashem/echo-operator:v0.0.2
                  ports:
                    - containerPort: 60000
                      name: metrics
                  command:
                  - echo-operator
                  imagePullPolicy: Always
                  env:
                    - name: WATCH_NAMESPACE
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.namespace
                    - name: OPERATOR_NAME
                      value: "echo-operator"
              restartPolicy: Always
              terminationGracePeriodSeconds: 5
              serviceAccountName: echo-operator
              serviceAccount: echo-operator
  customresourcedefinitions:
    owned:
      - description: Represents a cluster of echo apps
        displayName: Echo App
        kind: EchoApp
        name: echoapps.echo.redhat.com
        version: v1
        resources:
          - kind: Deployment
            version: v1beta2
          - kind: ReplicaSet
            version: v1beta2
          - kind: Pod
            version: v1
        specDescriptors:
          - description: The desired number of member Pods for the deployment.
            displayName: Size
            path: size
            x-descriptors:
              - 'urn:alm:descriptor:com.tectonic.ui:podCount'
        statusDescriptors:
          - description: The current status of the application.
            displayName: Status
            path: phase
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase'
          - description: Explanation for the current status of the application.
            displayName: Status Details
            path: reason
            x-descriptors:
              - 'urn:alm:descriptor:io.kubernetes.phase:reason'
  keywords:
    - echo
    - app
  displayName: Echo App
  provider:
    name: Red Hat
    url: www.redhat.com
  maturity: alpha
  version: 0.0.1
  maintainers:
    - email: corp@redhat.com
      name: Red Hat
  description: Platform for getting whatever you send echo'd
  labels:
    alm-owner-enterprise-app: echo-app-operator
    alm-status-descriptors: echo-app-operator.v0.0.1
